const RAW_POSTS = [
  {
    "id": "post_2026_09_01_1208",
    "label": "DMC x STR / interest meeting carousel",
    "type": "post_or_carousel",
    "date": "September 1",
    "time": "12:08 PM",
    "account": "dukemusiccollective",
    "durationSec": null,
    "views": 2886.0,
    "followerViewsPct": 0.557,
    "nonfollowerViewsPct": 0.443,
    "watchTimeSec": null,
    "avgWatchTimeSec": null,
    "skipRate": null,
    "typicalSkipRate": null,
    "interactions": 41.0,
    "followerInteractionsPct": 0.878,
    "nonfollowerInteractionsPct": 0.122,
    "likes": 28.0,
    "comments": 0.0,
    "shares": 8.0,
    "reposts": 1.0,
    "saves": 4.0,
    "profileActivity": 37.0,
    "profileVisits": 28.0,
    "externalLinkTaps": 8.0,
    "follows": 1.0,
    "audienceMenPct": 0.416,
    "audienceWomenPct": 0.584,
    "interactionRate": 0.014206514206514207,
    "shareRate": 0.002772002772002772,
    "saveRate": 0.001386001386001386,
    "matchStatus": "matched",
    "notes": "All visible metrics reconcile: 28 likes + 0 comments + 8 shares + 1 repost + 4 saves = 41 interactions."
  },
  {
    "id": "post_2026_09_01_1530",
    "label": "Duke Music Day",
    "type": "post_or_carousel",
    "date": "September 1",
    "time": "3:30 PM",
    "account": "cdjatduke and 2 others",
    "durationSec": null,
    "views": 6748.0,
    "followerViewsPct": 0.321,
    "nonfollowerViewsPct": 0.679,
    "watchTimeSec": null,
    "avgWatchTimeSec": null,
    "skipRate": null,
    "typicalSkipRate": null,
    "interactions": 135.0,
    "followerInteractionsPct": 0.431,
    "nonfollowerInteractionsPct": 0.569,
    "likes": 108.0,
    "comments": 5.0,
    "shares": 16.0,
    "reposts": 4.0,
    "saves": 2.0,
    "profileActivity": null,
    "profileVisits": null,
    "externalLinkTaps": null,
    "follows": null,
    "audienceMenPct": null,
    "audienceWomenPct": null,
    "interactionRate": 0.02000592768227623,
    "shareRate": 0.0023710729104919974,
    "saveRate": 0.0002963841138114997,
    "matchStatus": "matched",
    "notes": "All visible interaction metrics reconcile to 135."
  },
  {
    "id": "post_2026_09_02_1621",
    "label": "DMC x STR / interest meeting",
    "type": "post_or_carousel",
    "date": "September 2",
    "time": "4:21 PM",
    "account": "dukemusiccollective",
    "durationSec": null,
    "views": 3581.0,
    "followerViewsPct": null,
    "nonfollowerViewsPct": null,
    "watchTimeSec": null,
    "avgWatchTimeSec": null,
    "skipRate": null,
    "typicalSkipRate": null,
    "interactions": 46.0,
    "followerInteractionsPct": null,
    "nonfollowerInteractionsPct": null,
    "likes": 37.0,
    "comments": 1.0,
    "shares": 8.0,
    "reposts": 0.0,
    "saves": 0.0,
    "profileActivity": null,
    "profileVisits": null,
    "externalLinkTaps": null,
    "follows": null,
    "audienceMenPct": 0.437,
    "audienceWomenPct": 0.563,
    "interactionRate": 0.012845573862049707,
    "shareRate": 0.002234012845573862,
    "saveRate": 0.0,
    "matchStatus": "matched",
    "notes": "All visible interaction metrics reconcile to 46."
  },
  {
    "id": "post_2026_09_03_1040",
    "label": "Duke Music Day / committee announcements",
    "type": "post_or_carousel",
    "date": "September 3",
    "time": "10:40 AM",
    "account": "dukemusiccollective",
    "durationSec": null,
    "views": 2444.0,
    "followerViewsPct": 0.64,
    "nonfollowerViewsPct": 0.36,
    "watchTimeSec": null,
    "avgWatchTimeSec": null,
    "skipRate": null,
    "typicalSkipRate": null,
    "interactions": 38.0,
    "followerInteractionsPct": null,
    "nonfollowerInteractionsPct": null,
    "likes": 31.0,
    "comments": 0.0,
    "shares": 5.0,
    "reposts": 1.0,
    "saves": 1.0,
    "profileActivity": null,
    "profileVisits": null,
    "externalLinkTaps": null,
    "follows": null,
    "audienceMenPct": 0.418,
    "audienceWomenPct": 0.582,
    "interactionRate": 0.015548281505728314,
    "shareRate": 0.0020458265139116204,
    "saveRate": 0.0004091653027823241,
    "matchStatus": "matched",
    "notes": "All visible interaction metrics reconcile to 38."
  },
  {
    "id": "post_2026_09_12_1234",
    "label": "Duke Music Day",
    "type": "carousel",
    "date": "September 12",
    "time": "12:34 PM",
    "account": "dukemusiccollective and 3 others",
    "durationSec": null,
    "views": 30158.0,
    "followerViewsPct": 0.269,
    "nonfollowerViewsPct": 0.731,
    "watchTimeSec": null,
    "avgWatchTimeSec": null,
    "skipRate": null,
    "typicalSkipRate": null,
    "interactions": 611.0,
    "followerInteractionsPct": 0.229,
    "nonfollowerInteractionsPct": 0.771,
    "likes": 318.0,
    "comments": 17.0,
    "shares": 226.0,
    "reposts": 22.0,
    "saves": 28.0,
    "profileActivity": null,
    "profileVisits": null,
    "externalLinkTaps": null,
    "follows": null,
    "audienceMenPct": 0.569,
    "audienceWomenPct": 0.431,
    "interactionRate": 0.02025996418860667,
    "shareRate": 0.0074938656409576235,
    "saveRate": 0.0009284435307381126,
    "matchStatus": "matched",
    "notes": "Duplicate screenshots were consolidated. All visible interaction metrics reconcile to 611."
  },
  {
    "id": "post_2026_09_15",
    "label": "Let the STR reels era begin",
    "type": "reel",
    "date": "September 15",
    "time": null,
    "account": "dukemusiccollective",
    "durationSec": 6.0,
    "views": 5568.0,
    "followerViewsPct": 0.115,
    "nonfollowerViewsPct": 0.885,
    "watchTimeSec": 18898.0,
    "avgWatchTimeSec": 6.0,
    "skipRate": 0.357,
    "typicalSkipRate": 0.611,
    "interactions": 151.0,
    "followerInteractionsPct": 0.429,
    "nonfollowerInteractionsPct": 0.571,
    "likes": 120.0,
    "comments": 9.0,
    "shares": 15.0,
    "reposts": 2.0,
    "saves": 5.0,
    "profileActivity": 4.0,
    "profileVisits": null,
    "externalLinkTaps": null,
    "follows": 4.0,
    "audienceMenPct": 0.82,
    "audienceWomenPct": 0.18,
    "interactionRate": 0.027119252873563218,
    "shareRate": 0.0026939655172413795,
    "saveRate": 0.0008979885057471264,
    "matchStatus": "matched",
    "notes": "All visible interaction metrics reconcile to 151."
  },
  {
    "id": "post_2026_09_17_1606",
    "label": "Post shown in screenshot",
    "type": "unknown",
    "date": "September 17",
    "time": "4:06 PM",
    "account": null,
    "durationSec": null,
    "views": 267.0,
    "followerViewsPct": 0.989,
    "nonfollowerViewsPct": 0.011,
    "watchTimeSec": null,
    "avgWatchTimeSec": null,
    "skipRate": null,
    "typicalSkipRate": null,
    "interactions": 3.0,
    "followerInteractionsPct": null,
    "nonfollowerInteractionsPct": null,
    "likes": null,
    "comments": null,
    "shares": null,
    "reposts": null,
    "saves": null,
    "profileActivity": 3.0,
    "profileVisits": 2.0,
    "externalLinkTaps": 1.0,
    "follows": 0.0,
    "audienceMenPct": 0.474,
    "audienceWomenPct": 0.526,
    "interactionRate": 0.011235955056179775,
    "shareRate": null,
    "saveRate": null,
    "matchStatus": "matched",
    "notes": "Interaction breakdown was not visible."
  },
  {
    "id": "post_2026_09_17_gothic_grill",
    "label": "GOTHIC GRILL TMRW 4PM",
    "type": "reel",
    "date": "September 17",
    "time": null,
    "account": "dukemusiccollective and 1 other",
    "durationSec": 16.0,
    "views": 4889.0,
    "followerViewsPct": null,
    "nonfollowerViewsPct": null,
    "watchTimeSec": 16064.0,
    "avgWatchTimeSec": 5.0,
    "skipRate": 0.708,
    "typicalSkipRate": null,
    "interactions": 101.0,
    "followerInteractionsPct": 0.125,
    "nonfollowerInteractionsPct": 0.875,
    "likes": 72.0,
    "comments": 5.0,
    "shares": 19.0,
    "reposts": 4.0,
    "saves": 1.0,
    "profileActivity": null,
    "profileVisits": null,
    "externalLinkTaps": null,
    "follows": null,
    "audienceMenPct": 0.632,
    "audienceWomenPct": 0.368,
    "interactionRate": 0.020658621394968296,
    "shareRate": 0.003886275311924729,
    "saveRate": 0.00020454080589077522,
    "matchStatus": "matched",
    "notes": "The header showed 73 likes, but the detailed interaction page showed 72; 72 is used because it reconciles exactly to 101 interactions."
  },
  {
    "id": "post_2026_09_18_artist_manager",
    "label": "Artist Manager Applications Close",
    "type": "reel",
    "date": "September 18",
    "time": null,
    "account": null,
    "durationSec": 23.0,
    "views": 1086.0,
    "followerViewsPct": 0.263,
    "nonfollowerViewsPct": 0.737,
    "watchTimeSec": 4793.0,
    "avgWatchTimeSec": 7.0,
    "skipRate": 0.692,
    "typicalSkipRate": 0.604,
    "interactions": 34.0,
    "followerInteractionsPct": 0.8,
    "nonfollowerInteractionsPct": 0.2,
    "likes": 27.0,
    "comments": 1.0,
    "shares": 3.0,
    "reposts": 0.0,
    "saves": 3.0,
    "profileActivity": 0.0,
    "profileVisits": null,
    "externalLinkTaps": null,
    "follows": null,
    "audienceMenPct": 0.538,
    "audienceWomenPct": 0.462,
    "interactionRate": 0.03130755064456722,
    "shareRate": 0.0027624309392265192,
    "saveRate": 0.0027624309392265192,
    "matchStatus": "matched",
    "notes": "The header showed 28 likes and 2 comments, while the detailed page showed 27 likes and 1 comment; detailed values are used because they reconcile exactly to 34 interactions."
  },
  {
    "id": "unidentified_post_236_views",
    "label": "Unidentified post; header not supplied",
    "type": "unknown",
    "date": null,
    "time": null,
    "account": null,
    "durationSec": null,
    "views": 236.0,
    "followerViewsPct": null,
    "nonfollowerViewsPct": null,
    "watchTimeSec": null,
    "avgWatchTimeSec": null,
    "skipRate": null,
    "typicalSkipRate": null,
    "interactions": 5.0,
    "followerInteractionsPct": null,
    "nonfollowerInteractionsPct": null,
    "likes": null,
    "comments": null,
    "shares": null,
    "reposts": null,
    "saves": null,
    "profileActivity": 9.0,
    "profileVisits": null,
    "externalLinkTaps": null,
    "follows": null,
    "audienceMenPct": null,
    "audienceWomenPct": null,
    "interactionRate": 0.0211864406779661,
    "shareRate": null,
    "saveRate": null,
    "matchStatus": "partial_unmatched",
    "notes": "The screenshot did not include the post header, so it could not be safely matched to another record."
  },
  {
    "id": "unmatched_audience_001",
    "label": "Unmatched audience screenshot",
    "type": "unknown",
    "date": null,
    "time": null,
    "account": null,
    "durationSec": null,
    "views": null,
    "followerViewsPct": null,
    "nonfollowerViewsPct": null,
    "watchTimeSec": null,
    "avgWatchTimeSec": null,
    "skipRate": null,
    "typicalSkipRate": null,
    "interactions": null,
    "followerInteractionsPct": null,
    "nonfollowerInteractionsPct": null,
    "likes": null,
    "comments": null,
    "shares": null,
    "reposts": null,
    "saves": null,
    "profileActivity": null,
    "profileVisits": null,
    "externalLinkTaps": null,
    "follows": null,
    "audienceMenPct": 0.556,
    "audienceWomenPct": 0.444,
    "interactionRate": null,
    "shareRate": null,
    "saveRate": null,
    "matchStatus": "partial_unmatched",
    "notes": "The screenshot contained only gender percentages and could not be safely linked to a post."
  },
  {
    "id": "unmatched_audience_002",
    "label": "Unmatched audience screenshot",
    "type": "unknown",
    "date": null,
    "time": null,
    "account": null,
    "durationSec": null,
    "views": null,
    "followerViewsPct": null,
    "nonfollowerViewsPct": null,
    "watchTimeSec": null,
    "avgWatchTimeSec": null,
    "skipRate": null,
    "typicalSkipRate": null,
    "interactions": null,
    "followerInteractionsPct": null,
    "nonfollowerInteractionsPct": null,
    "likes": null,
    "comments": null,
    "shares": null,
    "reposts": null,
    "saves": null,
    "profileActivity": null,
    "profileVisits": null,
    "externalLinkTaps": null,
    "follows": null,
    "audienceMenPct": 0.447,
    "audienceWomenPct": 0.553,
    "interactionRate": null,
    "shareRate": null,
    "saveRate": null,
    "matchStatus": "partial_unmatched",
    "notes": "The screenshot contained only gender percentages and could not be safely linked to a post."
  }
];
export default RAW_POSTS;
