import { useState } from 'react';
import StickerCard from './StickerCard';
import { SectionHeading } from './TopPerformanceCards';

export default function CampaignGenerator({ goalHint }) {
  const [loading, setLoading] = useState(false);
  const [campaign, setCampaign] = useState(null);
  const [source, setSource] = useState(null);
  const [error, setError] = useState(null);

  async function handleGenerate() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/generate-campaign', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ goal: goalHint }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Request failed');
      setCampaign(data.campaign);
      setSource(data.source);
    } catch (e) {
      setError('Could not generate a campaign right now. Please try again.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <section className="mx-auto max-w-6xl px-6 py-10">
      <SectionHeading eyebrow="Section 7" title="AI campaign generator" />
      <StickerCard className="mt-6" tilt="tilt-3">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <p className="max-w-xl text-sm text-creamdim">
            Generates a full six-post campaign — teaser through follow-up — built around your current goal selection above.
          </p>
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="label-tag whitespace-nowrap rounded border border-moss bg-moss px-6 py-3 text-sm text-cream shadow-[3px_3px_0_rgba(0,0,0,0.35)] transition-opacity hover:opacity-90 disabled:opacity-50"
          >
            {loading ? 'Building campaign…' : 'Generate campaign'}
          </button>
        </div>
        {error && <p className="mt-3 text-sm text-rust">{error}</p>}
        {source && (
          <p className="mt-3 text-xs text-creamdim">
            {source === 'ai' ? 'Generated by AI.' : 'Generated locally (no AI API key configured, or the AI request failed) — still grounded in the dataset.'}
          </p>
        )}
      </StickerCard>

      {campaign && (
        <div className="mt-6 flex gap-5 overflow-x-auto scrollbar-thin pb-4">
          {campaign.posts.map((p, i) => (
            <StickerCard
              key={i}
              tilt={i % 2 === 0 ? 'tilt-1' : 'tilt-3'}
              className="min-w-[260px] max-w-[260px] flex-shrink-0"
              tape={i === 0}
            >
              <span className="label-tag rounded border border-rust/50 bg-rust/15 px-2 py-0.5 text-[10px] uppercase tracking-wide text-rust">
                {i + 1}. {p.stage}
              </span>
              <p className="mt-3 text-sm leading-relaxed text-cream">{p.idea}</p>
              <dl className="mt-4 space-y-2 text-xs">
                <div>
                  <dt className="label-tag text-creamdim">Format</dt>
                  <dd className="mt-0.5 text-cream">{p.format}</dd>
                </div>
                <div>
                  <dt className="label-tag text-creamdim">Hook</dt>
                  <dd className="scrawl mt-0.5 text-base text-rust">{p.hook}</dd>
                </div>
                <div>
                  <dt className="label-tag text-creamdim">Call to action</dt>
                  <dd className="mt-0.5 text-cream">{p.cta}</dd>
                </div>
                <div>
                  <dt className="label-tag text-creamdim">Goal</dt>
                  <dd className="mt-0.5 text-cream">{p.goal}</dd>
                </div>
                <div>
                  <dt className="label-tag text-creamdim">Success metric</dt>
                  <dd className="mt-0.5 text-moss">{p.metric}</dd>
                </div>
              </dl>
            </StickerCard>
          ))}
        </div>
      )}
    </section>
  );
}
