import { useState } from 'react';
import StickerCard from './StickerCard';
import { SectionHeading } from './TopPerformanceCards';

export default function IdeaGenerator({ goalHint }) {
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [ideas, setIdeas] = useState(null);
  const [source, setSource] = useState(null);
  const [error, setError] = useState(null);

  async function handleGenerate() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/generate-ideas', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ goal: input || goalHint }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Request failed');
      setIdeas(data.ideas);
      setSource(data.source);
    } catch (e) {
      setError('Could not generate ideas right now. Please try again.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <section className="mx-auto max-w-6xl px-6 py-10">
      <SectionHeading eyebrow="Section 6" title="AI content idea generator" />
      <StickerCard className="mt-6" tilt="tilt-1">
        <p className="text-sm text-creamdim">
          Describe a goal in your own words. AI generates new ideas grounded in what has performed well so far — it doesn&apos;t just summarize past posts.
        </p>
        <div className="mt-4 flex flex-col gap-3 sm:flex-row">
          <input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="e.g. Promote an upcoming STR event and maximize Duke undergraduate attendance"
            className="flex-1 rounded border border-cream/20 bg-charcoal px-4 py-3 text-sm text-cream placeholder:text-creamdim/60 focus:border-rust focus:outline-none"
          />
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="label-tag whitespace-nowrap rounded border border-rust bg-rust px-6 py-3 text-sm text-cream shadow-[3px_3px_0_rgba(0,0,0,0.35)] transition-opacity hover:opacity-90 disabled:opacity-50"
          >
            {loading ? 'Generating…' : 'Generate 3 ideas'}
          </button>
        </div>
        {error && <p className="mt-3 text-sm text-rust">{error}</p>}
        {source && (
          <p className="mt-3 text-xs text-creamdim">
            {source === 'ai' ? 'Generated by AI.' : 'Generated locally (no AI API key configured, or the AI request failed) — still grounded in the dataset.'}
          </p>
        )}
      </StickerCard>

      {ideas && (
        <div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-3">
          {ideas.map((idea, i) => (
            <StickerCard key={i} tilt={i % 2 === 0 ? 'tilt-2' : 'tilt-4'} pin={i === 1}>
              <h3 className="font-display text-lg leading-snug text-cream">{idea.title}</h3>
              <dl className="mt-4 space-y-3 text-sm">
                <Field label="Format" value={idea.format} />
                <Field label="Hook" value={idea.hook} accent />
                <Field label="Caption concept" value={idea.captionConcept} />
                <Field label="Target audience" value={idea.targetAudience} />
                <Field label="Expected outcome" value={idea.expectedOutcome} />
                <div>
                  <dt className="label-tag text-creamdim">Metrics to track</dt>
                  <dd className="mt-1 flex flex-wrap gap-1.5">
                    {(idea.metrics || []).map((m) => (
                      <span key={m} className="rounded-full border border-moss/40 bg-moss/15 px-2 py-0.5 text-xs text-moss">
                        {m}
                      </span>
                    ))}
                  </dd>
                </div>
                <Field label="Why this fits past performance" value={idea.whyItFits} />
              </dl>
            </StickerCard>
          ))}
        </div>
      )}
    </section>
  );
}

function Field({ label, value, accent }) {
  if (!value) return null;
  return (
    <div>
      <dt className="label-tag text-xs uppercase tracking-wide text-creamdim">{label}</dt>
      <dd className={`mt-1 leading-relaxed ${accent ? 'scrawl text-xl text-rust' : 'text-cream'}`}>{value}</dd>
    </div>
  );
}
